import { useEffect, useState } from "react";
import AdminShell from "@/components/AdminShell";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useToast } from "@/hooks/use-toast";

const db = supabase as any;
type Method = { id?: string; method_type: string; label: string; iban: string; account_holder_name: string; bank_name: string; entity_name: string; entity_number: string; phone_number: string; instructions: string; is_active: boolean };
type Subscription = { id: string; user_id: string; payment_id: string; proof_path: string; status: string; plan?: { name: string; price_kz: number }; profile?: { full_name: string; email: string } };
const blank: Method = { method_type: "bank_transfer", label: "Transferência bancária", iban: "", account_holder_name: "", bank_name: "", entity_name: "", entity_number: "", phone_number: "", instructions: "", is_active: true };

export default function AdminPayments({ mode = "admin" }: { mode?: "admin" | "sub" }) {
  const { user } = useAuth(); const { toast } = useToast(); const [method, setMethod] = useState<Method>(blank); const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [proofs, setProofs] = useState<Record<string, string>>({});
  const load = async () => { const [{ data: methods }, { data: rows }, { data: plans }, { data: profiles }] = await Promise.all([db.from("payment_methods").select("*").eq("is_active", true).limit(1), db.from("plan_subscriptions").select("id,user_id,plan_id,proof_path,status,created_at").eq("status", "pending").order("created_at", { ascending: true }), db.from("subscription_plans").select("id,name,price_kz"), db.from("profiles").select("user_id,full_name,email")]); const current = methods?.[0]; if (current) setMethod(current); const planMap = new Map((plans || []).map((plan: any) => [plan.id, plan])); const profileMap = new Map((profiles || []).map((profile: any) => [profile.user_id, profile])); setSubscriptions((rows || []).map((row: any) => ({ ...row, plan: planMap.get(row.plan_id), profile: profileMap.get(row.user_id) }))); };
  useEffect(() => { void load(); }, []);
  const save = async () => { const payload = { ...method, id: undefined, updated_by: user?.id }; const result = method.id ? await db.from("payment_methods").update(payload).eq("id", method.id) : await db.from("payment_methods").insert(payload); if (result.error) return toast({ title: "Erro", description: result.error.message, variant: "destructive" }); toast({ title: "Dados de pagamento guardados" }); load(); };
  const viewProof = async (row: Subscription) => { const { data, error } = await supabase.storage.from("payment-proofs").createSignedUrl(row.proof_path, 3600); if (error) return toast({ title: "Erro", description: error.message, variant: "destructive" }); setProofs((current) => ({ ...current, [row.id]: data.signedUrl })); };
  const confirm = async (id: string) => { const { data, error } = await db.rpc("confirm_plan_subscription", { p_subscription_id: id, p_actor_id: user?.id, p_reference: null }); if (error || data?.error) return toast({ title: "Erro", description: error?.message || data?.error, variant: "destructive" }); toast({ title: "Pagamento confirmado", description: "A conta foi ativada no plano escolhido." }); load(); };
    return <AdminShell title="Pagamentos e planos" mode={mode}><Card><CardHeader><CardTitle>Dados apresentados aos clientes</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><div><Label>Tipo</Label><select className="mt-2 w-full rounded-md border bg-background p-2" value={method.method_type} onChange={(e) => setMethod({ ...method, method_type: e.target.value })}><option value="bank_transfer">Transferência bancária</option><option value="entity">Referência / entidade</option></select></div><div><Label>Nome apresentado</Label><Input value={method.label} onChange={(e) => setMethod({ ...method, label: e.target.value })} /></div></div><div className="grid gap-4 md:grid-cols-2"><div><Label>IBAN</Label><Input value={method.iban} onChange={(e) => setMethod({ ...method, iban: e.target.value })} /></div><div><Label>Nome do titular</Label><Input value={method.account_holder_name} onChange={(e) => setMethod({ ...method, account_holder_name: e.target.value })} /></div><div><Label>Banco</Label><Input value={method.bank_name} onChange={(e) => setMethod({ ...method, bank_name: e.target.value })} /></div><div><Label>Nome da entidade</Label><Input value={method.entity_name} onChange={(e) => setMethod({ ...method, entity_name: e.target.value })} /></div><div><Label>Número da entidade</Label><Input value={method.entity_number} onChange={(e) => setMethod({ ...method, entity_number: e.target.value })} /></div><div><Label>Telefone</Label><Input value={method.phone_number} onChange={(e) => setMethod({ ...method, phone_number: e.target.value })} /></div></div><div><Label>Instruções</Label><Textarea value={method.instructions} onChange={(e) => setMethod({ ...method, instructions: e.target.value })} /></div><Button onClick={save}>Guardar dados</Button></CardContent></Card><Card><CardHeader><CardTitle>Comprovativos pendentes</CardTitle></CardHeader><CardContent className="space-y-3">{subscriptions.length === 0 && <p className="text-sm text-muted-foreground">Nenhum comprovativo pendente.</p>}{subscriptions.map((row) => <div key={row.id} className="rounded-md border p-4"><div className="font-semibold">{row.profile?.full_name || row.profile?.email || row.user_id}</div><div className="text-sm text-muted-foreground">Plano {row.plan?.name} · {Number(row.plan?.price_kz || 0).toLocaleString("pt-AO")} Kz</div><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" onClick={() => viewProof(row)}>Visualizar comprovativo</Button><Button onClick={() => confirm(row.id)}>Confirmar pagamento</Button></div>{proofs[row.id] && <a className="mt-3 block text-sm text-primary underline" href={proofs[row.id]} target="_blank" rel="noreferrer">Abrir comprovativo</a>}</div>)}</CardContent></Card></AdminShell>;
}
