import { Link } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowRight, Bot, CalendarDays, Check, LayoutDashboard, MessageCircle, Package, ShoppingBag, Store, UsersRound } from "lucide-react";
import aiImage from "@/assets/landing/ai-trained-business.png";
import storeImage from "@/assets/online-store.jpg";
import { MessagePacks } from "@/components/home/MessagePacks";
import FAQSection from "@/components/home/FAQSection";

const steps = [["01", "Crie a sua conta", "Registe-se gratuitamente e tenha acesso ao painel Muwoyo."], ["02", "Configure o seu negócio", "Adicione produtos, serviços, horários, regras e outras informações importantes."], ["03", "Teste gratuitamente", "Receba 100 mensagens gratuitas durante 3 dias para experimentar o Agente de IA na prática."], ["04", "Conecte o seu WhatsApp", "Ligue o número da sua empresa à Muwoyo através da plataforma."], ["05", "Escolha um plano", "Depois do teste, escolha o plano mensal adequado ao seu negócio."], ["06", "Continue a crescer", "Acompanhe a sua operação com as ferramentas da Muwoyo."]];
const capabilities = [[MessageCircle, "Atendimento com IA", "Responda perguntas frequentes, consulte informações do negócio e mantenha as conversas ativas."], [Package, "Produtos e catálogo", "Apresente produtos, preços, detalhes e disponibilidade diretamente aos clientes."], [ShoppingBag, "Pedidos", "Registe e organize os pedidos recebidos através do WhatsApp."], [CalendarDays, "Agendamentos", "Organize reservas, marcações e atendimentos de forma simples."], [UsersRound, "Gestão de clientes", "Organize leads e informações importantes das conversas."], [LayoutDashboard, "Painel Muwoyo", "Acompanhe as principais informações da sua operação num único lugar."]];
const audiences = [[Store, "Clínicas", "Organize marcações, dúvidas frequentes e atendimento aos pacientes pelo WhatsApp."], [ShoppingBag, "Boutiques", "Apresente produtos, preços, disponibilidade e receba pedidos sem perder conversas."], [CalendarDays, "Prestadores de serviços", "Automatize informações, orçamentos, agendamentos e confirmações."], [UsersRound, "Qualquer negócio", "Se atende clientes pelo WhatsApp, use a Muwoyo em qualquer nicho."]];
const checks = (items: string[]) => <ul className="mt-5 grid gap-3 text-[#526174] sm:grid-cols-2">{items.map((item) => <li key={item} className="flex items-start gap-2"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#169c78]" />{item}</li>)}</ul>;

export default function LandingContent() {
  return <>
    <section id="features" className="py-20 lg:py-28"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">O problema</p><h2 className="mt-3 max-w-3xl text-3xl font-bold tracking-tight text-[#142235] md:text-5xl">O problema não é receber clientes. É conseguir responder a todos.</h2><div className="mt-5 max-w-3xl space-y-4 text-lg leading-relaxed text-[#526174]"><p>Quando várias mensagens chegam ao mesmo tempo, responder a cada cliente pode tornar-se difícil. Perguntas sobre preços, produtos, disponibilidade, localização, horários e serviços repetem-se todos os dias.</p><p>Enquanto a equipa tenta acompanhar todas as conversas, algumas mensagens ficam sem resposta. E quando um cliente espera demasiado, pode simplesmente procurar outra empresa.</p></div></div></section>
    <section className="bg-[#eaf7ef] py-20 lg:py-28"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">A solução</p><h2 className="mt-3 max-w-3xl text-3xl font-bold tracking-tight text-[#142235] md:text-5xl">A solução é transformar o seu WhatsApp num canal inteligente que trabalha com a sua equipa.</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-[#526174]">A Muwoyo utiliza Inteligência Artificial para assumir parte do atendimento diário. A IA pode responder perguntas, apresentar produtos e serviços, organizar informações, ajudar a receber pedidos, agendar atendimentos e manter as conversas ativas.</p><p className="mt-4 max-w-3xl text-lg leading-relaxed text-[#526174]">Enquanto a Muwoyo cuida das tarefas repetitivas, a sua equipa pode concentrar-se nos clientes e situações que realmente precisam de atenção humana.</p><div className="mt-7 border-l-2 border-[#5dce8d] pl-5 font-semibold text-[#142235]">Atendimento automatizado. Sem perder o controlo da sua empresa.<p className="mt-2 text-[#169c78]">A Muwoyo não substitui a sua equipa. Ajuda a sua equipa a trabalhar melhor.</p></div></div></section>
    <section id="funcionalidades" className="bg-[#f8faf9] py-20 lg:py-28"><div className="container mx-auto grid max-w-6xl items-center gap-12 px-6 lg:grid-cols-2"><motion.div initial={{ opacity: 0, x: -24 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }}><img src={aiImage} alt="IA Muwoyo adaptada ao negócio" className="w-full rounded-2xl border border-[#e6ece9] bg-white object-contain shadow-sm" /></motion.div><div><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Inteligência Artificial</p><h2 className="mt-3 text-3xl font-bold tracking-tight text-[#142235] md:text-4xl">Uma IA que conhece o seu negócio.</h2><p className="mt-2 text-xl font-semibold text-[#169c78]">A sua empresa fornece o conhecimento.</p><p className="mt-5 text-lg leading-relaxed text-[#526174]">Adicione produtos, preços, serviços, horários, regras, formas de pagamento e outras informações importantes. A IA utiliza esses dados para responder aos clientes com contexto e de acordo com a forma como o seu negócio funciona.</p>{checks(["Produtos e preços", "Serviços e horários", "Regras de atendimento", "Formas de pagamento"])}<p className="mt-6 font-semibold text-[#142235]">A sua empresa mantém a sua identidade. A Muwoyo automatiza o trabalho repetitivo.</p></div></div></section>
    <section id="como-funciona" className="bg-[#eaf7ef] py-16 text-[#142235] lg:py-20"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Como funciona</p><h2 className="mt-3 text-3xl font-bold md:text-5xl">Da criação da conta ao atendimento automatizado.</h2><p className="mt-5 max-w-3xl text-lg text-[#526174]">Comece gratuitamente, configure o seu negócio e coloque a automação a trabalhar no seu WhatsApp.</p><div className="relative mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-3">{steps.map(([number, title, description]) => <div key={number} className="border-t border-[#b8ddc5] pt-5"><span className="text-sm font-bold text-[#169c78]">{number}</span><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-[#526174]">{description}</p></div>)}</div><Link to="/criar-conta" className="mt-8 inline-flex items-center gap-2 rounded-xl bg-[#169c78] px-6 py-3 font-semibold text-white hover:bg-[#128565]">Criar conta gratuitamente <ArrowRight className="h-4 w-4" /></Link></div></section>
    <section className="bg-[#f8faf9] py-20 lg:py-28"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Capacidades</p><h2 className="mt-3 text-3xl font-bold text-[#142235] md:text-5xl">Muito mais do que responder mensagens.</h2><p className="mt-5 max-w-3xl text-lg text-[#526174]">A Muwoyo reúne ferramentas para ajudar a sua empresa a atender, vender e organizar o trabalho num único lugar.</p><div className="mt-10 grid gap-x-10 gap-y-8 sm:grid-cols-2">{capabilities.map(([Icon, title, description]) => <div key={title as string} className="flex items-start gap-4 border-t border-[#e3e9e5] pt-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#ddf4e5] text-[#169c78]"><Icon className="h-5 w-5" /></span><div><h3 className="font-semibold text-[#142235]">{title as string}</h3><p className="mt-1 text-sm leading-relaxed text-[#526174]">{description as string}</p></div></div>)}</div></div></section>
    <section className="py-20 lg:py-24"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Para quem é</p><h2 className="mt-3 max-w-3xl text-3xl font-bold text-[#142235] md:text-4xl">Feita para negócios que vendem e atendem pelo WhatsApp.</h2><p className="mt-5 max-w-3xl text-lg text-[#526174]">A Muwoyo adapta-se a diferentes tipos de negócio e ajuda a automatizar tarefas de atendimento, vendas e organização.</p><div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{audiences.map(([Icon, title, description]) => <div key={title as string} className="border-t border-[#e3e9e5] pt-5"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#eaf7ef] text-[#169c78]"><Icon className="h-5 w-5" /></span><h3 className="mt-4 font-semibold text-[#142235]">{title as string}</h3><p className="mt-2 text-sm leading-relaxed text-[#526174]">{description as string}</p></div>)}</div><p className="mt-8 font-semibold text-[#169c78]">Se os seus clientes utilizam WhatsApp para falar com a sua empresa, a Muwoyo pode ajudar.</p></div></section>
    <section className="bg-[#eaf7ef] py-16 lg:py-20"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Tudo num só lugar</p><h2 className="mt-3 max-w-3xl text-3xl font-bold text-[#142235] md:text-4xl">A sua operação já vem pronta na Muwoyo.</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-[#526174]">Não precisa conectar Google Sheets, Calendar ou outras integrações externas para começar. A Muwoyo já inclui ferramentas próprias para atendimento com IA, cadastro de clientes e produtos, pedidos, agendamentos e uma loja online.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Bot, "Atender clientes", "Automatize conversas."], [UsersRound, "Gerir clientes", "Organize leads."], [Package, "Gerir produtos", "Cadastre preços e detalhes."], [ShoppingBag, "Organizar pedidos", "Registe e acompanhe pedidos."], [CalendarDays, "Gerir agendamentos", "Organize horários e reservas."], [Store, "Criar uma loja online", "Uma loja gratuita e personalizável."]].map(([Icon, title, description]) => <div key={title as string} className="flex items-start gap-3 border-b border-[#b8ddc5] pb-5"><Icon className="mt-1 h-5 w-5 shrink-0 text-[#169c78]" /><div><h3 className="font-semibold text-[#142235]">{title as string}</h3><p className="mt-1 text-sm text-[#526174]">{description as string}</p></div></div>)}</div></div></section>
    <section className="bg-white py-20 lg:py-24"><div className="container mx-auto grid max-w-6xl items-center gap-10 px-6 lg:grid-cols-2"><div className="overflow-hidden rounded-2xl border border-[#e3e9e5] bg-[#f8faf9] p-3"><img src={storeImage} alt="Loja online personalizada da Muwoyo" className="w-full rounded-xl object-cover" /></div><div><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Loja online</p><h2 className="mt-3 text-3xl font-bold text-[#142235] md:text-4xl">Uma loja online gratuita e personalizável.</h2><p className="mt-5 text-lg leading-relaxed text-[#526174]">Além da automação de atendimento e vendas no WhatsApp, a Muwoyo oferece uma loja online totalmente gratuita. Personalize a identidade visual, cadastre produtos, partilhe o link ou QR Code e mantenha tudo ligado ao seu atendimento.</p>{checks(["Sem custo adicional", "Identidade visual", "Produtos cadastrados", "Link exclusivo", "QR Code", "Ligação ao WhatsApp"])}<div className="mt-6 border-l-2 border-[#5dce8d] pl-4"><p className="font-semibold text-[#142235]">A loja cresce consigo e pode ser personalizada sempre que o seu negócio mudar.</p></div><Link to="/criar-conta" className="mt-7 inline-flex rounded-xl bg-[#169c78] px-6 py-3 font-semibold text-white hover:bg-[#128565]">Criar a minha conta gratuitamente</Link></div></div></section>
    <section className="py-20 lg:py-24"><div className="container mx-auto max-w-6xl px-6"><p className="text-sm font-semibold uppercase tracking-wider text-[#169c78]">Comunidade Muwoyo</p><h2 className="mt-3 text-3xl font-bold text-[#142235] md:text-4xl">Faça parte da Comunidade Muwoyo.</h2><p className="mt-5 max-w-3xl text-lg leading-relaxed text-[#526174]">Aprenda, partilhe experiências, descubra novidades e evolua com outros empreendedores que utilizam tecnologia para melhorar os seus negócios.</p><div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[[UsersRound, "Aprenda", "Estratégias e boas práticas."], [MessageCircle, "Partilhe", "Experiências e ideias."], [Package, "Descubra", "Novidades e funcionalidades."], [Bot, "Evolua", "Tecnologia aplicada aos negócios."]].map(([Icon, title, description]) => <div key={title as string} className="border-t border-[#e3e9e5] pt-5"><Icon className="h-5 w-5 text-[#169c78]" /><h3 className="mt-3 font-semibold text-[#142235]">{title as string}</h3><p className="mt-1 text-sm text-[#526174]">{description as string}</p></div>)}</div></div></section>
    <MessagePacks />
    <div id="faq"><FAQSection /></div>
    <section className="bg-[#eaf7ef] py-20 text-center text-[#142235] lg:py-24"><div className="container mx-auto max-w-4xl px-6"><h2 className="text-3xl font-bold md:text-5xl">O seu próximo cliente não deveria esperar pela sua resposta.</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-relaxed text-[#526174]">Crie a sua conta gratuitamente, configure o seu negócio e experimente o Agente de IA na prática.</p><Link to="/criar-conta" className="mt-8 inline-flex items-center justify-center gap-2 rounded-xl bg-[#169c78] px-7 py-3 font-bold text-white hover:bg-[#128565]">Criar conta gratuitamente <ArrowRight className="h-4 w-4" /></Link></div></section>
  </>;
}
