create table if not exists public.n8n_chat_histories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  phone_number text not null,
  session_id text not null,
  message jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.n8n_chat_histories
  add column if not exists user_id uuid references auth.users(id) on delete cascade,
  add column if not exists phone_number text;

create index if not exists n8n_chat_histories_session_idx
  on public.n8n_chat_histories(user_id, session_id, created_at);
alter table public.n8n_chat_histories enable row level security;
drop policy if exists n8n_chat_histories_user_policy on public.n8n_chat_histories;
create policy n8n_chat_histories_user_policy on public.n8n_chat_histories
  for select to authenticated using (auth.uid() = user_id);

alter table public.appointments
  add column if not exists location text,
  add column if not exists price numeric(12,2),
  add column if not exists duration_minutes integer,
  add column if not exists notes text;

alter table public.store_orders
  add column if not exists payment_status text default 'pending',
  add column if not exists delivery_address text;

alter table public.appointments enable row level security;
alter table public.store_orders enable row level security;
drop policy if exists appointments_user_policy on public.appointments;
drop policy if exists store_orders_user_policy on public.store_orders;
create policy appointments_user_policy on public.appointments
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy store_orders_user_policy on public.store_orders
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.inbox_conversations;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.whatsapp_contacts;
exception when duplicate_object then null;
end $$;
do $$
begin
  alter publication supabase_realtime add table public.inbox_contact_presence;
exception when duplicate_object then null;
end $$;
